"""FastAPI inference service for the clinical LLM.

Endpoints
---------
* ``GET  /health``      liveness + which model is loaded
* ``POST /chat``        single-shot completion (JSON in, JSON out)
* ``POST /chat/stream`` token-streaming completion (text/event-stream)
* ``GET  /``            a minimal browser chat UI (served from ../../../ui)

The model is loaded once at startup from environment variables (see
``inference.load_from_env``). Run with::

    uvicorn clinical_llm.serve.app:app --host 0.0.0.0 --port 8000
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from fastapi import FastAPI
from fastapi.responses import HTMLResponse, StreamingResponse
from pydantic import BaseModel, Field

from clinical_llm.data.formatting import SYSTEM_PROMPT
from clinical_llm.serve.inference import ClinicalLLM, GenerationSettings, load_from_env
from clinical_llm.utils.logging import get_logger

log = get_logger("serve")

app = FastAPI(title="Clinical-LLM", version="0.1.0")
_MODEL: Optional[ClinicalLLM] = None

# Medical-safety disclaimer appended to every API response payload. Belt-and-
# braces alongside the system-prompt framing baked into training.
DISCLAIMER = (
    "This output is generated by a research language model and is NOT medical "
    "advice. It may be incorrect. Verify against primary sources and defer to a "
    "licensed clinician."
)


class ChatRequest(BaseModel):
    message: str = Field(..., description="user turn")
    history: list[dict] = Field(default_factory=list, description="prior [{'role','content'}] turns")
    system: str = Field(default=SYSTEM_PROMPT)
    max_new_tokens: int = 512
    temperature: float = 0.3
    top_p: float = 0.9


class ChatResponse(BaseModel):
    reply: str
    disclaimer: str = DISCLAIMER


def get_model() -> ClinicalLLM:
    global _MODEL
    if _MODEL is None:
        log.info("loading model on first request ...")
        _MODEL = load_from_env()
        log.info("model loaded on device=%s", _MODEL.device)
    return _MODEL


@app.on_event("startup")
def _startup() -> None:
    # Eager-load unless explicitly deferred (deferring speeds up test startup).
    import os

    if os.environ.get("CLINICAL_LLM_LAZY", "0") != "1":
        get_model()


@app.get("/health")
def health() -> dict:
    loaded = _MODEL is not None
    return {
        "status": "ok",
        "model_loaded": loaded,
        "device": _MODEL.device if loaded else None,
    }


def _settings(req: ChatRequest) -> GenerationSettings:
    return GenerationSettings(
        max_new_tokens=req.max_new_tokens,
        temperature=req.temperature,
        top_p=req.top_p,
    )


@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest) -> ChatResponse:
    model = get_model()
    reply = model.generate(req.message, history=req.history, system=req.system, settings=_settings(req))
    return ChatResponse(reply=reply)


@app.post("/chat/stream")
def chat_stream(req: ChatRequest) -> StreamingResponse:
    model = get_model()

    def event_gen():
        for token in model.stream(
            req.message, history=req.history, system=req.system, settings=_settings(req)
        ):
            yield f"data: {json.dumps({'token': token})}\n\n"
        yield f"data: {json.dumps({'done': True, 'disclaimer': DISCLAIMER})}\n\n"

    return StreamingResponse(event_gen(), media_type="text/event-stream")


@app.get("/", response_class=HTMLResponse)
def index() -> str:
    ui = Path(__file__).resolve().parents[3] / "ui" / "index.html"
    if ui.exists():
        return ui.read_text(encoding="utf-8")
    return "<h1>Clinical-LLM</h1><p>UI file not found; POST to /chat.</p>"
